global:
  scrape_interval: 15s # Tần suất thu thập dữ liệu từ các dịch vụ

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323'] # Docker Daemon Metrics
  - job_name: 'spring-boot'
    static_configs:
      - targets: [ 'localhost:8080' ]